#!/usr/bin/env python3
import socket
import sys

from bmp import BMPMsg


HOST, PORT = "192.0.2.10", 1789
def main():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind((HOST, PORT))
        s.listen()
        conn, addr = s.accept()

        try:
            while True:
                data = conn.recv(4096)
                while len(data) > BMPMsg.MIN_LEN:
                    data = BMPMsg.dissect(data)
        except Exception as e:
            print(e)
        except KeyboardInterrupt:
            pass
        finally:
            conn.close()

if __name__ == "__main__":
    sys.exit(main())
